# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_account', models.IntegerField()),
                ('personal_account', models.IntegerField()),
                ('nominal_account', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='accounttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountType'),
            preserve_default=False,
        ),
    ]
