# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160105_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='trial_balance',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group'),
            preserve_default=False,
        ),
    ]
